[package]
name = "ssd_sn_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
lazy_static = "1.4"
thiserror = "1.0"  # 添加 thiserror 依赖